export const BOOK_DBSEARCH_REQUEST = "BOOK_DBSEARCH_REQUEST";
export const BOOK_DBSEARCH_SUCCESS = "BOOK_DBSEARCH_SUCCESS";
export const BOOK_DBSEARCH_FAILURE = "BOOK_DBSEARCH_FAILURE";

export const BOOK_DBDELETE_REQUEST = "BOOK_DBDELETE_REQUEST";
export const BOOK_DBDELETE_SUCCESS = "BOOK_DBDELETE_SUCCESS";
export const BOOK_DBDELETE_FAILURE = "BOOK_DBDELETE_FAILURE";

// google API constants
export const BOOK_GAPI_SEARCH_REQUEST = "BOOK_GAPI_SEARCH_REQUEST";
export const BOOK_GAPI_SEARCH_SUCCESS = "BOOK_GAPI_SEARCH_SUCCESS";
export const BOOK_GAPI_SEARCH_FAILURE = "BOOK_GAPI_SEARCH_FAILURE";
